config/routes.rb
Rails.application.routes.draw do

  root to: 'courses#index'
  resources :courses

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :destroy]

  def index
    @course = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to root_path
    else
      redirect_to edit_course_path(@course)
    end
  end

  def destroy
    @course = Course.find(params[:id])
    if @course.destroy
      redirect_to root_path
    end
  end

  def show
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:courseID, :course_name, :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="col-6 mx-auto">
  <%= form_with(model: course, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :courseID %>
    <%= form.text_field :courseID, id: :courseID, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= form.label :course_name %>
    <%= form.text_field :course_name, id: :course_name, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= form.label :group_id %>
     <%#= select_tag(:group_id,{},Group.all,:id,:group_name) %>
    <%= form.collection_select :group_id, Group.all, :id, :group_name, {},class: 'form-control' %>
  </div>
  <div class="actions">
    <%#= form.submit :SAVE, id: :submit, class: 'btn btn-primary' %>
    <button type="submit" class="btn btn-primary">SAVE</button>
    <button type="reset" class="btn btn-warning">CANCEL</button>
  </div>
  <% end -%>
</div>

app/views/courses/create.html.erb
<h1>Courses#create</h1>
<p>Find me in app/views/courses/create.html.erb</p>

app/views/courses/destroy.html.erb
<h1>Courses#destroy</h1>
<p>Find me in app/views/courses/destroy.html.erb</p>

app/views/courses/edit.html.erb
<%= render 'form', course: @course %>

app/views/courses/index.html.erb
<div class="col-12 mr-auto">
  <div class="float-right"><%= link_to( fa_icon('plus', text: 'Course'), new_course_path , class: 'btn btn-primary') %></div>
  <table class="table table-striped table-hover">
    <caption>Course Data Table</caption>
    <thead class="bg-secondary text-center">
      <tr>
        <th>#</th>
        <th>CourseID</th>
        <th>CourseName</th>
        <th>GroupName</th>
        <th>#</th>
      </tr>
    </thead>
    <tbody class="text-center">
      <% num = 0 %>
      <% @course.each do |course| %>
      <tr>
        <td><%= num +=1 %></td>
        <td><%= course.courseID %></td>
        <td><%= course.course_name %></td>
        <td><%= course.group.group_name %></td>
        <td>
          <%= link_to( fa_icon("pencil"), edit_course_path(course), class: 'btn btn-warning btn-sm') %>
          <%= link_to (fa_icon "trash"), course_path(course), class: 'btn btn-danger btn-sm',  method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/courses/new.html.erb
<%= render 'form', course: @course  %>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>

app/views/courses/update.html.erb
<h1>Courses#update</h1>
<p>Find me in app/views/courses/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>GeExam</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light alert-info " style="margin-bottom: 10px;">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand row" href="/">สำนักศึกษาทั่วไป มหาวิทยาลัยราชภัฎอุดรธานี</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
     </div>
     <div class="collapse navbar-collapse " id="navbarSupportedContent">
       <ul class="nav navbar-nav  ml-auto">
         <li class="nav-item active">
          <%= link_to (fa_icon "tachometer",text: 'ทั่วไป'), root_path, class: 'nav-link', title: 'ทั่วไป' %>
        </li>
        <li class="nav-item">
          <%= link_to (fa_icon "plus-circle", text: 'เพิ่ม course'), new_course_path, class: 'nav-link', title: 'เพิ่ม course' %>
        </li>
        <li class="nav-item">
          <%= link_to (fa_icon "graduation-cap", text: 'นศ.ที่ขอสอบ'), courses_path, class: 'nav-link', title: 'นักศึกษาที่ขอสอบ' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid col-10 bg-light" style="padding: 10px 5px 5px 5px;">
  <%= yield %>
</div>

</body>
</html>